const ShopActionTypes = {
  FECTCH_COLLECTIONS_START: "FECTCH_COLLECTIONS_START",
  FECTCH_COLLECTIONS_SUCCESS: 'FECTCH_COLLECTIONS_SUCCESS',
  FECTCH_COLLECTIONS_FAILURE: 'FECTCH_COLLECTIONS_FAILURE',
};

export default ShopActionTypes;
