const UserActionTypes = {
  GOOGLE_SING_IN_START: "GOOGLE_SING_IN_START",
  EMAIL_SING_IN_START: "EMAIL_SING_IN_START",
  SING_IN_SUCCESS: "SING_IN_SUCCESS",
  SING_IN_FAILURE: "SING_IN_FAILURE",
};

export default UserActionTypes