const UserActionTypes = {
  GOOGLE_SING_IN_START: "GOOGLE_SING_IN_START",
  EMAIL_SING_IN_START: "EMAIL_SING_IN_START",
  SING_IN_SUCCESS: "SING_IN_SUCCESS",
  SING_IN_FAILURE: "SING_IN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SING_OUT_START: "SING_OUT_START",
  SING_OUT_SUCCESS: "SING_OUT_SUCCESS",
  SING_OUT_FAILURE: "SING_OUT_FAILURE",
};

export default UserActionTypes;
