const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SING_IN_START: "GOOGLE_SING_IN_START",
  GOOGLE_SING_IN_SUCCESS: "GOOGLE_SING_IN_SUCCESS",
  GOOGLE_SING_IN_FAILURE: "GOOGLE_SING_IN_FAILURE",
  EMAIL_SING_IN_START: "EMAIL_SING_IN_START",
  EMAIL_SING_IN_SUCCESS: "EMAIL_SING_IN_SUCCESS",
  EMAIL_SING_IN_FAILURE: "EMAIL_SING_IN_FAILURE",
};

export default UserActionTypes